/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppListRouteImport } from './routes/_app/list'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppTopicsIndexRouteImport } from './routes/_app/topics/index'
import { Route as AppTopicsTopicSlugRouteImport } from './routes/_app/topics/$topicSlug'
import { Route as AppPhotosPhotoIdRouteImport } from './routes/_app/photos/$photoId'
import { Route as AppCollectionsCollectionIdRouteImport } from './routes/_app/collections/$collectionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppListRoute = AppListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsIndexRoute = AppTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsTopicSlugRoute = AppTopicsTopicSlugRouteImport.update({
  id: '/topics/$topicSlug',
  path: '/topics/$topicSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosPhotoIdRoute = AppPhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsCollectionIdRoute =
  AppCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/favorites': typeof AppFavoritesRoute
  '/list': typeof AppListRoute
  '/search': typeof AppSearchRoute
  '/collections/$collectionId': typeof AppCollectionsCollectionIdRoute
  '/photos/$photoId': typeof AppPhotosPhotoIdRoute
  '/topics/$topicSlug': typeof AppTopicsTopicSlugRoute
  '/topics/': typeof AppTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof AppFavoritesRoute
  '/list': typeof AppListRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/collections/$collectionId': typeof AppCollectionsCollectionIdRoute
  '/photos/$photoId': typeof AppPhotosPhotoIdRoute
  '/topics/$topicSlug': typeof AppTopicsTopicSlugRoute
  '/topics': typeof AppTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/list': typeof AppListRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/collections/$collectionId': typeof AppCollectionsCollectionIdRoute
  '/_app/photos/$photoId': typeof AppPhotosPhotoIdRoute
  '/_app/topics/$topicSlug': typeof AppTopicsTopicSlugRoute
  '/_app/topics/': typeof AppTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/list'
    | '/search'
    | '/collections/$collectionId'
    | '/photos/$photoId'
    | '/topics/$topicSlug'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favorites'
    | '/list'
    | '/search'
    | '/'
    | '/collections/$collectionId'
    | '/photos/$photoId'
    | '/topics/$topicSlug'
    | '/topics'
  id:
    | '__root__'
    | '/_app'
    | '/_app/favorites'
    | '/_app/list'
    | '/_app/search'
    | '/_app/'
    | '/_app/collections/$collectionId'
    | '/_app/photos/$photoId'
    | '/_app/topics/$topicSlug'
    | '/_app/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/list': {
      id: '/_app/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof AppListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/': {
      id: '/_app/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof AppTopicsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/$topicSlug': {
      id: '/_app/topics/$topicSlug'
      path: '/topics/$topicSlug'
      fullPath: '/topics/$topicSlug'
      preLoaderRoute: typeof AppTopicsTopicSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos/$photoId': {
      id: '/_app/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/photos/$photoId'
      preLoaderRoute: typeof AppPhotosPhotoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/$collectionId': {
      id: '/_app/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof AppCollectionsCollectionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppListRoute: typeof AppListRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCollectionsCollectionIdRoute: typeof AppCollectionsCollectionIdRoute
  AppPhotosPhotoIdRoute: typeof AppPhotosPhotoIdRoute
  AppTopicsTopicSlugRoute: typeof AppTopicsTopicSlugRoute
  AppTopicsIndexRoute: typeof AppTopicsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppListRoute: AppListRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCollectionsCollectionIdRoute: AppCollectionsCollectionIdRoute,
  AppPhotosPhotoIdRoute: AppPhotosPhotoIdRoute,
  AppTopicsTopicSlugRoute: AppTopicsTopicSlugRoute,
  AppTopicsIndexRoute: AppTopicsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
